{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}

{{- if and .Values.hpa .Values.hpa.enabled }}

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ $name }}
  namespace: {{ $namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
  {{- if eq (.Values.type | lower) "deployment" }}
    kind: Deployment
  {{- else if eq (.Values.type | lower) "cronjob" }}
    kind: CronJob
  {{- end }}
    name: {{ $name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}

{{- end }}
