{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}
{{- $ctx := dict "name" $name "Values" .Values "namespace" $namespace "imageName" .Values.image.name "imageTag" .Values.image.tag -}}
{{- if and .Values.command .Values.command.enabled }}
  {{- $_ := set $ctx "command" .Values.command -}}
  {{- $_ := set $ctx "commandEnabled" .Values.command.enabled -}}
{{- end }}
{{- if eq (.Values.type | lower) "cronjob" -}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $name }}
    area: {{ .Values.area | default "psi" | quote }}
    chart_version: {{ .Values.chart_version }}
  {{- include "base_webserver.annotations" (dict "ctx" . "annotation" .Values.annotations "area" .Values.area) | nindent 2 }}
spec:
  schedule: "{{ .Values.crontab }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $name }}
            area: {{ .Values.area | default "psi" | quote }}
            chart_version: {{ .Values.chart_version }}

      {{- include "base_webserver.annotations" (dict "ctx" . "annotation" .Values.annotationsPod "area" .Values.area) | nindent 10 }}
        spec:
        
          {{- if or (and .Values.allowExecutionWithRoot (not .Values.allowExecutionWithRoot.enabled)) (not .Values.allowExecutionWithRoot) }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          {{- end }}
          restartPolicy: OnFailure
          {{- if and .Values.hostAliases .Values.hostAliases.enabled }}
          hostAliases:
            {{- toYaml .Values.hostAliases.aliases | nindent 12 }}
          {{- end }}
          containers:
{{- include "base_webserver.deploy-body" $ctx | nindent 10 }}
{{- include "base_webserver.deploy-volume" $ctx | nindent 10 }}
{{- end }}