{{- $namespace := .Values.group | replace "." "" -}}
{{- $name := .Values.project -}}
{{- $port := .Values.port -}}

{{- if $port }}

apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $name }}
    area: {{ .area | default "psi" | quote }}
  namespace: {{ $namespace }}
  name: {{ $namespace }}-{{ $name }}-service
spec:
  type: ClusterIP
  ports:
    - port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: TCP
      name: {{ $name }}-{{ $port.port }}-port
  selector:
    app: {{ $name }}

{{- end }}