apiVersion: v2
appVersion: 1.0.0
description: |
  Chart de base para servidores web. Features:
  - secretos en Vault
  - autenticación en harbor
  - HPA en prod
  - PVC - volumen en NFS
  - configmaps en volúmenes
  - despliegue con deployment o argo rollouts
  - cronjob para ejecutar tareas de manera programada
  - annotations para reloader y APM
  - multiples hosts
  - ingress con whitelist
  - oauth2-proxy para autenticación de usuarios
name: base_webserver
type: application
version: 4.3.0
